//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCY_SURVICES
    {
        public int IDSERVICES { get; set; }
        public int IDAGENCY { get; set; }
        public Nullable<double> BEGIN_PRICE { get; set; }
        public Nullable<double> MAX_PRICE { get; set; }
    
        public virtual AGENCY AGENCY { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
