//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENCY()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.AGENCY_SOCIAL = new HashSet<AGENCY_SOCIAL>();
            this.IMGAGENCies = new HashSet<IMGAGENCY>();
            this.ORDERs = new HashSet<ORDER>();
            this.SERVICES = new HashSet<SERVICE>();
            this.CATEGORies = new HashSet<CATEGORY>();
        }
    
        public int IDAGENCY { get; set; }
        public string NAMEAGENCY { get; set; }
        public string PHONEAGENCY { get; set; }
        public string ADDRESSAGENCY { get; set; }
        public string EMAILAGENCY { get; set; }
        public string SUMARYAGENCY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> IDSOCIAL { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public int IDUSER { get; set; }
        public int IDCATE { get; set; }
        public Nullable<int> IDPEOPLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENCY_SOCIAL> AGENCY_SOCIAL { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMGAGENCY> IMGAGENCies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE> SERVICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORY> CATEGORies { get; set; }
    }
}
