//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOANCHUYENNGANHEntities : DbContext
    {
        public DOANCHUYENNGANHEntities()
            : base("name=DOANCHUYENNGANHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENCY> AGENCies { get; set; }
        public virtual DbSet<AGENCY_SOCIAL> AGENCY_SOCIAL { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<COMMENT> COMMENTs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<EVENT_SERVICE> EVENT_SERVICE { get; set; }
        public virtual DbSet<EVENT> EVENTS { get; set; }
        public virtual DbSet<IMGAGENCY> IMGAGENCies { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<ORDER> ORDERs { get; set; }
        public virtual DbSet<ORDER_HISTORY> ORDER_HISTORY { get; set; }
        public virtual DbSet<ORDER_INFO> ORDER_INFO { get; set; }
        public virtual DbSet<Person> PEOPLE { get; set; }
        public virtual DbSet<POSITION> POSITIONs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<SERVICE> SERVICES { get; set; }
        public virtual DbSet<SOCIAL> SOCIALs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIME_EVENT> TIME_EVENT { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
