//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEOPLE_AGENCY
    {
        public int IDAGENCY { get; set; }
        public int IDPEOPLE { get; set; }
        public Nullable<int> TEAM_MEMBER { get; set; }
    
        public virtual AGENCY AGENCY { get; set; }
        public virtual Person Person { get; set; }
    }
}
