//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE()
        {
            this.EVENTS = new HashSet<EVENT>();
        }
    
        public int IDSERVICES { get; set; }
        public string NAMESERVICES { get; set; }
        public string SUMARYSERVICES { get; set; }
        public Nullable<int> BEGIN_PRICE { get; set; }
        public Nullable<int> MAX_PRICE { get; set; }
        public int IDAGENCY { get; set; }
    
        public virtual AGENCY AGENCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT> EVENTS { get; set; }
    }
}
